### ISSUE TITLE
TypeError: ('Keyword argument not understood:', 'crop_to_aspect_ratio') in TensorFlow 2.5.0

### ISSUE THREAD

**Issue by FAFUpear** [yuanyuan-qwq/TomaTrac#1]
TensorFlow version 2.5.0 does not support the crop_to_aspect_ratio parameter. Could you please provide your latest requirements.txt file? TypeError: ('Keyword argument not understood:', 'crop_to_aspect_ratio')

**Comment by yuanyuan-qwq** [comment]
can i know your Python version

**Comment by yuanyuan-qwq** [comment]
or you can try using conda to match the version another version 

or try this

tensorflow>=2.6.0
numpy>=1.19.5
pandas>=1.3.3
matplotlib>=3.4.3
scipy>=1.7.1
scikit-learn>=0.24.2
h5py>=3.1.0
Pillow>=8.3.2

**Comment by FAFUpear** [comment]
My Python version is 3.8. I attempted to upgrade to tensorflow==2.11.0 yesterday, but it produced an error related to an unmatched fn parameter.
`[nltk_data]   Package wordnet is already up-to-date!
2024-08-17 17:16:13.863870: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "myapi.py", line 52, in <module>
    CNN_MODEL = tf.keras.models.load_model("CNN\\tomato12v3.h5")
  File "D:\Anaconda\envs\wangs\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\Anaconda\envs\wangs\lib\site-packages\keras\losses.py", line 315, in from_config
    return cls(**config)
TypeError: __init__() got an unexpected keyword argument 'fn'
`

**Comment by FAFUpear** [comment]
> or you can try using conda to match the version another version
> 
> or try this
> 
> tensorflow>=2.6.0 numpy>=1.19.5 pandas>=1.3.3 matplotlib>=3.4.3 scipy>=1.7.1 scikit-learn>=0.24.2 h5py>=3.1.0 Pillow>=8.3.2

I tried using TensorFlow==2.6.0, but it throws an exception:`raise ValueError: Unknown optimizer: Custom>Adam. Please ensure this object is passed to the custom_objects argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details`
Is Custom>Adam a custom optimizer that you defined?

**Comment by FAFUpear** [comment]
@yuanyuan-qwq Or would you be willing to provide Docker？

**Comment by yuanyuan-qwq** [comment]
absl-py==1.4.0
afinn==0.1
aiohttp==3.9.0
aiosignal==1.3.1
anyio==3.7.1
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
astunparse==1.6.3
async-lru==2.0.4
attrs==23.1.0
Babel==2.12.1
backcall==0.2.0
bbox-visualizer==0.1.0
beautifulsoup4==4.12.2
bleach==6.0.0
blinker==1.6.3
blis==0.7.11
cachetools==5.3.1
catalogue==2.0.10
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
cloudpathlib==0.16.0
colorama==0.4.6
comm==0.1.3
confection==0.1.4
contourpy==1.1.0
cycler==0.11.0
cymem==2.0.8
debugpy==1.6.7
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.7
distro==1.8.0
dm-tree==0.1.8
emoji==2.9.0
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl#sha256=86cc141f63942d4b2c5fcee06630fd6f904788d2f0ab005cce45aadb8fb73889
et-xmlfile==1.1.0
executing==1.2.0
fastapi==0.104.0
fastjsonschema==2.18.0
filelock==3.12.4
Flask==3.0.0
Flask-MySQLdb==2.0.0
flatbuffers==23.5.26
fonttools==4.41.1
fqdn==1.5.1
frozenlist==1.4.0
fsspec==2023.10.0
fuzzy-c-means==1.7.0
gast==0.4.0
gensim==4.3.2
gitdb==4.0.11
GitPython==3.1.40
google-auth==2.22.0
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
grpcio==1.56.2
h11==0.14.0
h5py==3.9.0
httpcore==1.0.2
httptools==0.6.1
httpx==0.25.2
huggingface-hub==0.19.4
idna==3.4
imbalanced-learn==0.11.0
install==1.3.5
ipykernel==6.25.0
ipython==8.14.0
ipython-genutils==0.2.0
ipywidgets==8.1.0
isoduration==20.11.0
itsdangerous==2.1.2
jedi==0.19.0
Jinja2==3.1.2
joblib==1.3.1
json5==0.9.14
jsonpointer==2.4
jsonschema==4.18.4
jsonschema-specifications==2023.7.1
jupyter==1.0.0
jupyter-bbox-widget==0.5.0
jupyter-console==6.6.3
jupyter-events==0.7.0
jupyter-lsp==2.2.0
jupyter_client==8.3.0
jupyter_core==5.3.1
jupyter_server==2.7.0
jupyter_server_terminals==0.4.4
jupyterlab==4.0.3
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.8
jupyterlab_server==2.24.0
keras==2.15.0
kiwisolver==1.4.4
langcodes==3.3.0
libclang==16.0.6
lxml==5.0.0
Markdown==3.4.4
MarkupSafe==2.1.3
matplotlib==3.7.2
matplotlib-inline==0.1.6
mistune==3.0.1
ml-dtypes==0.2.0
mock==5.1.0
mpmath==1.3.0
multidict==6.0.4
murmurhash==1.0.10
mysqlclient==2.2.0
nbclient==0.8.0
nbconvert==7.7.3
nbformat==5.9.2
nest-asyncio==1.5.7
networkx==3.2.1
nltk==3.8.1
notebook==7.0.1
notebook_shim==0.2.3
numpy==1.24.3
oauthlib==3.2.2
onnx==1.15.0
openai==0.28.0
opencv-python==4.8.1.78
openpyxl==3.1.2
opt-einsum==3.3.0
overrides==7.3.1
packaging==23.1
pandas==2.0.3
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
pillow==10.4.0
platformdirs==3.10.0
preshed==3.0.9
prometheus-client==0.17.1
prompt-toolkit==3.0.39
protobuf==3.20.3
psutil==5.9.5
pure-eval==0.2.2
py-cpuinfo==9.0.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
pydantic==1.10.12
Pygments==2.15.1
pylabel==0.1.55
pynput==1.7.6
pyparsing==3.0.9
PyQt5==5.15.10
PyQt5-Qt5==5.15.2
PyQt5-sip==12.13.0
python-dateutil==2.8.2
python-dotenv==1.0.0
python-json-logger==2.0.7
python-multipart==0.0.6
pytz==2023.3
pywinpty==2.0.11
PyYAML==6.0.1
pyzmq==25.1.0
qtconsole==5.4.3
QtPy==2.3.1
referencing==0.30.0
regex==2023.10.3
requests==2.32.3
requests-oauthlib==1.3.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.9.2
rsa==4.9
safetensors==0.4.0
scikit-learn==1.3.0
scipy==1.11.1
seaborn==0.12.2
Send2Trash==1.8.2
six==1.16.0
smart-open==6.4.0
smmap==5.0.1
sniffio==1.3.0
soupsieve==2.4.1
spacy==3.7.2
spacy-legacy==3.0.12
spacy-loggers==1.0.5
srsly==2.4.8
stack-data==0.6.2
starlette==0.27.0
sympy==1.12
tabulate==0.8.10
tensorboard==2.15.2
tensorboard-data-server==0.7.1
tensorflow==2.15.0
tensorflow-estimator==2.15.0
tensorflow-hub==0.14.0
tensorflow-intel==2.15.0
tensorflow-io-gcs-filesystem==0.31.0
tensorflow-model-optimization==0.7.5
tensorflow-recommenders==0.7.3
tensorflow-serving-api==2.5.0
termcolor==2.3.0
terminado==0.17.1
text2emotion==0.0.5
tf2onnx==1.15.1
thinc==8.2.2
thop==0.1.1.post2209072238
threadpoolctl==3.2.0
tinycss2==1.2.1
tokenizers==0.15.0
torch==2.1.1
torchvision==0.16.1
tornado==6.3.2
tqdm==4.65.0
traitlets==5.9.0
transformers==4.35.2
typer==0.4.2
typing_extensions==4.8.0
tzdata==2023.3
ultralytics==8.2.79
ultralytics-thop==2.0.5
uri-template==1.3.0
urllib3==1.26.16
utils==1.0.1
uvicorn==0.23.2
vaderSentiment==3.3.2
virtualenv==20.24.5
wasabi==1.1.2
watchfiles==0.21.0
wcwidth==0.2.6
weasel==0.3.4
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.1
websockets==12.0
Werkzeug==3.0.0
widgetsnbextension==4.0.8
wordcloud==1.9.2
wrapt==1.14.1
yarl==1.9.3

this is my full package
